services:
  webapi:
    image: findfi-webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5064:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://mongodb:27017
      - MongoDb__DatabaseName=reviews_core
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: findfi-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
